# fly.toml app configuration file generated for mailseek-web on 2025-03-08T22:26:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mailseek-web'
primary_region = 'fra'

[build]
  [build.args]
    NEXT_PUBLIC_BACKEND_URL="https://mailseek.fly.dev"
    NEXT_PUBLIC_URL="https://mailseek-web.fly.dev"
    NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bm5ham5kZ2x5ZHlpd2NrZHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTU1MDMsImV4cCI6MjA1NjkzMTUwM30.OSFOiXKhV9S7KnZ7DQuk22acSaiPizoe4qHBflfVfvA"
    NEXT_PUBLIC_SUPABASE_URL="https://gvnnajndglydyiwckdtn.supabase.co"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
